### ISSUE TITLE
Stanford Homographies

### ISSUE THREAD

**Issue by amiryanj** [dendorferpatrick/GoalGAN#3]
Hello @dendorferpatrick 
How did you get the homography matrices of the SDD dataset?

**Comment by dendorferpatrick** [comment]
Hi, 
the column "ratio" in the [H_SDD.txt](https://github.com/dendorferpatrick/GoalGAN/blob/master/datasets/stanford_synthetic/H_SDD.txt) gives you the pixel/ meter correspondence. Apparently, the authors did two measurements "version" ('A' and 'B') and we use 'version' ='A'. 
The pixes are given by the bird's-eye view image so we only multiply the pixel value with the ratio. 
In [trajectories.py](https://github.com/dendorferpatrick/GoalGAN/blob/master/data/trajectories.py) we rescale all scene images such that 1px => 0.05m.
